src/main/java/edu/eci/pdsw/samples/entities/Consulta.java
/*
 * Copyright (C) 2015 hcadavid
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package edu.eci.pdsw.samples.entities;

import java.sql.Date;

/**
 *
 * @author hcadavid
 */
public class Consulta {
    //el identificador es asignado por la base de datos,
    //por eso no se incluye en el constructor.
    private int id;
    
    private Date fechayHora;
    private String resumen;

    
    
    public Consulta(Date fechayHora, String resumen) {
        this.id=-1;
        this.fechayHora = fechayHora;
        this.resumen = resumen;
    }    
    
    public Consulta() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Date getFechayHora() {
        return fechayHora;
    }

    public void setFechayHora(Date fechayHora) {
        this.fechayHora = fechayHora;
    }

    public String getResumen() {
        return resumen;
    }

    public void setResumen(String resumen) {
        this.resumen = resumen;
    }

    @Override
    public String toString() {
        return "("+id+","+fechayHora+","+resumen+")"; //To change body of generated methods, choose Tools | Templates.
    }
    
    
}

src/main/java/edu/eci/pdsw/samples/entities/Paciente.java
/*
 * Copyright (C) 2015 hcadavid
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package edu.eci.pdsw.samples.entities;

import java.sql.Date;
import java.util.LinkedHashSet;
import java.util.Set;

/**
 *
 * @author hcadavid
 */
public class Paciente {
    
    private int id;
    private String tipo_id;
    private String nombre;
    private Date fechaNacimiento;
    Set<Consulta> consultas;
    

    public Paciente(int id, String tipo_id, String nombre, Date fechaNacimiento) {
        this.id = id;
        this.tipo_id = tipo_id;
        this.nombre = nombre;
        this.fechaNacimiento = fechaNacimiento;
        consultas=new LinkedHashSet<>();
    }

    public Paciente() {
        consultas=new LinkedHashSet<>();
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTipo_id() {
        return tipo_id;
    }

    public void setTipo_id(String tipo_id) {
        this.tipo_id = tipo_id;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Date getFechaNacimiento() {
        return fechaNacimiento;
    }

    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    public Set<Consulta> getConsultas() {
        return consultas;
    }

    public void setConsultas(Set<Consulta> consultas) {
        this.consultas = consultas;
    }

    @Override
    public String toString() {
        String rep="Paciente:["+id+","+tipo_id+","+nombre+","+fechaNacimiento+"]\n";
        for (Consulta c:consultas){
            rep+="\t["+c+"]\n";
        }
        return rep;
    }
    
    
    
}

src/main/java/edu/eci/pdsw/samples/managedbeans/RegistroConsultaBean.java
/*
 * Copyright (C) 2016 hcadavid
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package edu.eci.pdsw.samples.managedbeans;

import edu.eci.pdsw.samples.entities.Consulta;
import edu.eci.pdsw.samples.entities.Paciente;
import edu.eci.pdsw.samples.services.ExcepcionServiciosPacientes;
import edu.eci.pdsw.samples.services.ServiciosPacientes;
import java.io.IOException;
import java.io.Serializable;
import java.sql.Date;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.enterprise.context.SessionScoped;


/**
 *
 * @author hcadavid
 */

@ManagedBean (name="RegistroConsultaBean")
@SessionScoped

public class RegistroConsultaBean implements Serializable{
    
    //ServiciosPacientes sp=ServiciosPacientes.getInstance();
   
    private static ServiciosPacientes sp; 
    public RegistroConsultaBean() throws IOException, ExcepcionServiciosPacientes{
        
        sp=ServiciosPacientes.getInstance();
        
    }
    private Paciente tmp;
    private int id; 
    private String tipo_id;
    private String nombre; 
    private Date fecha_actual;
    private String consultacad;
    
    private Paciente seleccion;
    
    private String fechayhora;
    private Date fecha_total;
    private String Descripcion;
    private Consulta cons_temp;

    
    
    public void registrarPac() throws ExcepcionServiciosPacientes{
       fecha_actual = Date.valueOf(consultacad);
        tmp = new Paciente(id, tipo_id, nombre, fecha_actual);
         setId(0);
         setNombre("");
         setTipo_id("");
         setConsultacad(""); 
         sp.registrarNuevoPaciente(tmp);
    }
    public void agregarconsulta() throws ExcepcionServiciosPacientes{
        System.out.println("Entramos");
        seleccion = loadbyid(seleccion.getId(), seleccion.getTipo_id());
        sp.agregarConsultaAPaciente(seleccion.getId(), seleccion.getTipo_id(), cons_temp);
        
    }
    public List<Paciente> obtenerpacs(){
         List<Paciente> obtenerpacientes = sp.obtenerpacientes();return obtenerpacientes;
    }
    public Paciente getTmp() {
     
        return tmp;
    }
    public Paciente loadbyid(int id,String tipo){
      Paciente cargado=  sp.loadPaciente(id, tipo);
        return cargado;
    }

    public void setTmp(Paciente tmp) {
        this.tmp = tmp;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTipo_id() {
        return tipo_id;
    }

    public void setTipo_id(String tipo_id) {
        this.tipo_id = tipo_id;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Date getFecha_actual() {
        return fecha_actual;
    }

    public void setFecha_actual(Date fecha_actual) {
        this.fecha_actual = fecha_actual;
    }

    public String getConsultacad() {
        return consultacad;
    }

    public void setConsultacad(String consultacad) {
        this.consultacad = consultacad;
    }

    public Paciente getSeleccion() {
        if(seleccion==null){
            seleccion = new Paciente();
               return seleccion;
        }
        else{
        System.out.println("Seleccion:"+ seleccion.getNombre());
         seleccion = loadbyid(seleccion.getId(), seleccion.getTipo_id());
        return seleccion;}
    }

    public void setSeleccion(Paciente seleccion) {
        this.seleccion = seleccion;
    }

    public String getFechayhora() {
        return fechayhora;
    }

    public void setFechayhora(String fechayhora) {
        this.fechayhora = fechayhora;
    }

    public Date getFecha_total() {
        return fecha_total;
    }

    public void setFecha_total(Date fecha_total) {
        this.fecha_total = fecha_total;
    }

    public String getDescripcion() {
        return Descripcion;
    }

    public void setDescripcion(String Descripcion) {
        this.Descripcion = Descripcion;
    }

    public Consulta getCons_temp() {
         fecha_total=Date.valueOf(fechayhora);
        cons_temp=new Consulta(fecha_total,Descripcion);
        setFechayhora("");
        setDescripcion("");
       
        return cons_temp;
    }

    public void setCons_temp(Consulta cons_temp) {
        this.cons_temp = cons_temp;
    }
    

    public ServiciosPacientes getSp() {
        return sp;
    }

    public void setSp(ServiciosPacientes sp) {
        this.sp = sp;
    }
    
    
    
    
    
}

src/main/webapp/registroconsultas.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3c.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui" xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </h:head>
    <h:body>
    <h:form id = "frm_consulta">
        <script type="text/javascript">

        </script>
    
        <p:growl id="messages" showDetail="true">
            <p:panel id="pnl_addconsulta" header="Agregar una consulta" style="width: 600px;">
                <p:panelGrid columns="2" >
                         
                    <h:outputLabel id= "fechayhora" for="fechayhora" value= "fechayhora" />
                    <p:inputText value="#{RegistroConsultaBean.fechayhora}"></p:inputText>
                    
                    <h:outputLabel id= "Descripcion" for="Descripcion" value= "Descripcion:"/>
                    <p:inputText value="#{RegistroConsultaBean.descripcion}"></p:inputText>
                    
                    <f:facet name="footer">
                        <p:commandButton value="Agregar consulta" action ="#{RegistroConsultaBean.agregarconsulta()}"  update="pnl_addconsulta"/>
                    </f:facet>
                </p:panelGrid>
                
                
                <p:dataTable var="consulta" value ="#{RegistroConsultaBean.seleccion.consultas}" >
                     <f:facet name="header">
                        
                     </f:facet>
                    
                              <p:column headerText="Fecha y hora">
                                  <h:outputText value="#{consulta.fechayHora}"/>
                             </p:column>
                
                              <p:column headerText="Descripcion">
                                  <h:outputText value="#{consulta.resumen}"/>
                               </p:column>
                </p:dataTable> 
               
                
                <p:commandButton action="registropacientes?faces-redirect=true" value="Back"  />  
                
                
                
                
                
                
                                    
            </p:panel>
        </p:growl>
            </h:form>
    </h:body>
</html>

src/main/webapp/registropacientes.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"      
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      >
    <h:head>

        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </h:head>
    <h:body>

        <h:form id = "frm_paciente">
  <script type="text/javascript">

        </script>
            <p:growl id="messages" showDetail="true">
                <p:panel id="pnl_addpaciente" header="Agregar Paciente" style="width: 600px;"> 
                    <p:panelGrid columns="2" >
                        <h:outputLabel id= "id_pa" for="id_pa" value= "Identificacion Paciente"/>
                        <p:inputText value="#{RegistroConsultaBean.id}"></p:inputText>
                        <h:outputLabel id="tipo_id" for="tipo_id" value= "Tipo de Identificacion"/>
                        <p:inputText value="#{RegistroConsultaBean.tipo_id}"></p:inputText>
                        <h:outputLabel id="nombre" for="nombre" value= "Nombre"/>
                        <p:inputText value="#{RegistroConsultaBean.nombre}"></p:inputText>
                        <h:outputLabel id="dateconsultas" for="dateconsultas" value= "Fecha Nacimiento"/>
                        <p:inputText value="#{RegistroConsultaBean.consultacad}"></p:inputText>
                         <f:facet name="footer">
                             <p:commandButton value="Agregar Paciente" action ="#{RegistroConsultaBean.registrarPac()}"  update="dtb_pacientes"/>
                         </f:facet>
                </p:panelGrid>
               
                    <p:dataTable id="dtb_pacientes" var="paciente" value ="#{RegistroConsultaBean.obtenerpacs()}" selectionMode="single" selection="#{RegistroConsultaBean.seleccion}"  rowKey="#{paciente.id}">
                   <f:facet name="header">
                </f:facet>
                
                <p:column>
                    <p:commandButton  action="registroconsultas"  value="Registrar consulta"/>
                </p:column>
                
                <p:column headerText="Id">
                    <h:outputText value="#{paciente.id}"/>
                </p:column>
                
                <p:column headerText="Tipo">
                    <h:outputText value="#{paciente.tipo_id}"/>
                </p:column>
                
                <p:column headerText="Nombre">
                    <h:outputText value="#{paciente.nombre}"/>
                </p:column>
                         <p:column headerText="Fecha Nacimiento">
                             <h:outputText value="#{paciente.fechaNacimiento}"/>
                </p:column>            
            </p:dataTable>
                    
                  
                
                </p:panel>
            </p:growl>
        </h:form>
    </h:body>
</html>